Add support for Rails 8.0
rubysherpas/paranoia pull request #572
Opened 2024-12-05 09:09 UTC by chenillen

- add support to 8.0
- add a test all file for 6.1 - 8.0 version

2024-12-10 23:26 UTC, mathieujobin commented on .ruby-version
> +3.2.0
not sure why we need this file, especially with `.0` ...

2024-12-10 23:28 UTC, mathieujobin commented on lib/paranoia.rb
>    require 'paranoia/active_record_5_2'
looking at this change, this looks badly name... do we need this patch for rails 6, 7 and 8 ?

2024-12-10 23:29 UTC, mathieujobin commented on Gemfile
> +rails = ENV['RAILS'] || '~> 6.1.0'
we could move up the `rails` initialization, before `sqlite` and use the var instead, but I can see how its equivalent. so maybe its OK as-is

2024-12-10 23:34 UTC, mathieujobin reviewed
These looks like good changes... I only have minor comments... but the title is miss-leading. this isn't adding support for Rails 8. it's only fixing small things and adding a script. Support for 8 is already merged in #563

2025-02-12 07:50 UTC, chenillen commented on .ruby-version
> +3.2.0
Rails 8.0 requires at least 3.2.0 I think?

2025-03-05 02:38 UTC, mathieujobin commented on paranoia.gemspec
> +  s.required_ruby_version = '>= 3.2.0' if ENV['RAILS']&.start_with?('~> 8')  # Rails 8.0 requirement
+1

2025-03-05 02:38 UTC, mathieujobin requested changes
its missing the update to the workflow file, so that CI runs for the new rails/ruby combinaison

2025-03-16 14:27 UTC, mathieujobin commented on .ruby-version
> +3.2.0
that file isn't needed

2025-03-16 14:29 UTC, mathieujobin commented on Gemfile
> +rails = ENV['RAILS'] || '~> 6.1.0'
you should move up that line above `sqlite` so you can use it, allowing the default value.

2025-03-16 14:30 UTC, mathieujobin commented on Gemfile
> +  gem 'sqlite3', ENV['RAILS']&.start_with?('~> 8') ? '~> 2.1' : '~> 1.4', platforms: [:ruby]
I wonder, if `2.1+` works with rails 7 or 6, then we should turn the condition around and only use `~> 1.4` for older versions that don't support 2.x

2025-07-29 12:57 UTC, ghost commented
Hello,

> Support for 8 is already merged in https://github.com/rubysherpas/paranoia/pull/563

We're actually updating our codebase from 7.1 to 8.
And so far in the process, the bump from 7.2 to 8 is causing some trouble.
Anything I can do to help, because it appears it's not supporting Rails 8 yet 😅

2025-11-06 10:03 UTC, mathieujobin commented
thanks for your contribution.

2025-11-06 10:03 UTC, closed without merging